# Generated by Django 3.2 on 2021-05-14 22:57

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('is_active', models.BooleanField(default=True, help_text='Only active users are allowed to interact', verbose_name='active status')),
                ('is_admin', models.BooleanField(default=False, help_text='pyme or company admins can update the pymedata and manage its members.', verbose_name='pyme admin')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='nombre pyme')),
                ('business_name', models.CharField(max_length=150, verbose_name='razón social')),
                ('rut', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='rut of user  in the format: XXXXXXXX-X . Up to 10 digits allowed.', regex='^[0-9]+-[0-9kK]{1}$')])),
                ('address', models.CharField(max_length=150, verbose_name='direccion')),
                ('commune', models.CharField(blank=True, max_length=150, null=True, verbose_name='comuna')),
                ('state', models.CharField(blank=True, max_length=150, null=True, verbose_name='region')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
